import type { WorkspaceQueryRunner } from "./azure-service.js";
import { HuntingLibrary } from "./hunting-library.js";
import type { ShapedTable } from "./result-shaper.js";
import {
  entityTimelineQuery,
  entityTimelineSummaryQuery,
  incidentAlertsQuery,
  incidentDetailQuery,
  ingestionLatencyQuery,
  ingestionVolumeQuery,
  listIncidentsQuery,
  type EntityType,
  type IncidentFilters,
} from "./soc-queries.js";

// Built-in queries are generated by this server and may exceed the user query limit.
const builtInPolicy = { maxLength: 10_000, requireResultLimit: false };

export type Row = Record<string, unknown>;

export function tableToRows(table: ShapedTable | undefined): Row[] {
  if (!table) {
    return [];
  }
  return table.rows.map((row) =>
    Object.fromEntries(table.columns.map((column, index) => [column.name ?? `column${index}`, row[index]])),
  );
}

export interface PivotEntity {
  type: EntityType;
  value: string;
}

/**
 * Pulls account, IP and host entities out of SecurityAlert.Entities JSON so the client
 * can pivot straight into entity_timeline.
 */
export function extractPivotEntities(alerts: Row[]): PivotEntity[] {
  const seen = new Map<string, PivotEntity>();
  const add = (type: EntityType, value: unknown) => {
    if (typeof value === "string" && value.trim()) {
      seen.set(`${type}:${value.toLowerCase()}`, { type, value: value.trim() });
    }
  };

  for (const alert of alerts) {
    let entities: unknown;
    try {
      entities = typeof alert.Entities === "string" ? JSON.parse(alert.Entities) : alert.Entities;
    } catch {
      continue;
    }
    if (!Array.isArray(entities)) {
      continue;
    }
    for (const entity of entities as Row[]) {
      const kind = String(entity.Type ?? "").toLowerCase();
      if (kind === "account") {
        add("account", entity.UPNSuffix && entity.Name ? `${String(entity.Name)}@${String(entity.UPNSuffix)}` : entity.Name);
      } else if (kind === "ip") {
        add("ip", entity.Address);
      } else if (kind === "host") {
        add("host", entity.FQDN ?? (entity.DnsDomain && entity.HostName ? `${String(entity.HostName)}.${String(entity.DnsDomain)}` : entity.HostName));
      }
    }
  }
  return [...seen.values()];
}

export class SocService {
  constructor(
    private readonly runner: WorkspaceQueryRunner,
    private readonly hunting = new HuntingLibrary(),
  ) {}

  async #rows(workspaceId: string, query: string, timespan: string, policy = builtInPolicy) {
    const result = await this.runner.runQuery(workspaceId, query, timespan, policy);
    return { rows: tableToRows(result.tables[0]), truncatedRows: result.tables[0]?.truncatedRows ?? 0, status: result.status };
  }

  async listIncidents(workspaceId: string, timespan: string, filters: IncidentFilters) {
    const { rows } = await this.#rows(workspaceId, listIncidentsQuery(filters), timespan);
    return { count: rows.length, incidents: rows };
  }

  async getIncident(workspaceId: string, incidentNumber: number, timespan: string) {
    const [detail, alerts] = await Promise.all([
      this.#rows(workspaceId, incidentDetailQuery(incidentNumber), timespan),
      this.#rows(workspaceId, incidentAlertsQuery(incidentNumber), timespan),
    ]);
    if (!detail.rows[0]) {
      throw new Error(`KQL query found no incident ${incidentNumber} in the selected timespan. Widen the timespan or check the number.`);
    }
    return {
      incident: detail.rows[0],
      alerts: alerts.rows.map(({ Entities: _entities, ...alert }) => alert),
      pivotEntities: extractPivotEntities(alerts.rows),
    };
  }

  async entityTimeline(workspaceId: string, entityType: EntityType, entity: string, timespan: string, maxEvents: number) {
    const [summary, events] = await Promise.all([
      this.#rows(workspaceId, entityTimelineSummaryQuery(entityType, entity), timespan),
      this.#rows(workspaceId, entityTimelineQuery(entityType, entity, maxEvents), timespan),
    ]);
    return {
      entity: { type: entityType, value: entity },
      sources: summary.rows,
      totalEvents: summary.rows.reduce((total, row) => total + (Number(row.Events) || 0), 0),
      returnedEvents: events.rows.length,
      events: events.rows,
    };
  }

  async checkIngestionHealth(workspaceId: string, timespan: string, staleAfterHours: number) {
    const [volume, latency] = await Promise.all([
      this.#rows(workspaceId, ingestionVolumeQuery(staleAfterHours), timespan),
      this.#rows(workspaceId, ingestionLatencyQuery(), "PT1H"),
    ]);
    const problems = volume.rows.filter((row) => row.Status !== "Healthy");
    const delayed = latency.rows.filter((row) => Number(row.P95LatencySec) > 900);
    return {
      summary: {
        tables: volume.rows.length,
        stale: problems.filter((row) => row.Status === "Stale").map((row) => row.DataType),
        volumeDrops: problems.filter((row) => row.Status === "VolumeDrop").map((row) => row.DataType),
        volumeSpikes: problems.filter((row) => row.Status === "VolumeSpike").map((row) => row.DataType),
        delayedOver15Min: delayed.map((row) => row.TableName),
      },
      tables: volume.rows,
      latencyLastHour: latency.rows,
    };
  }

  listHuntingQueries() {
    return { queries: this.hunting.list(), loadErrors: this.hunting.loadErrors };
  }

  async runHuntingQuery(workspaceId: string, queryId: string, timespan: string) {
    const hunt = this.hunting.get(queryId);
    const { rows, truncatedRows } = await this.#rows(workspaceId, hunt.query, timespan, HuntingLibrary.policy);
    const { query: _query, ...metadata } = hunt;
    return { hunt: metadata, resultCount: rows.length, truncatedRows, results: rows };
  }
}
