import type { WorkspaceQueryRunner } from "./azure-service.js";
import { HuntingLibrary } from "./hunting-library.js";
import type { ShapedTable } from "./result-shaper.js";
import {
  entityTimelineQuery,
  entityTimelineSummaryQuery,
  incidentAlertsQuery,
  incidentDetailQuery,
  ingestionLatencyQuery,
  ingestionVolumeQuery,
  listIncidentsQuery,
  validateEntity,
  type EntityType,
  type IncidentFilters,
} from "./soc-queries.js";

// Built-in queries are generated by this server and may exceed the user query limit.
const builtInPolicy = { maxLength: 10_000, requireResultLimit: false };

export type Row = Record<string, unknown>;

export function tableToRows(table: ShapedTable | undefined): Row[] {
  if (!table) {
    return [];
  }
  return table.rows.map((row) =>
    Object.fromEntries(table.columns.map((column, index) => [column.name ?? `column${index}`, row[index]])),
  );
}

export interface PivotEntity {
  type: EntityType;
  value: string;
}

export interface UnresolvedEntity {
  type: EntityType;
  reason: string;
  label?: string;
}

const text = (value: unknown) => (typeof value === "string" && value.trim() ? value.trim() : undefined);

function isValidEntity(type: EntityType, value: string | undefined): value is string {
  if (!value) {
    return false;
  }
  try {
    validateEntity(type, value);
    return true;
  } catch {
    return false;
  }
}

/** Best pivotable identifier for an account entity, from most to least specific. */
function accountCandidates(entity: Row): Array<string | undefined> {
  const name = text(entity.Name);
  const suffix = text(entity.UPNSuffix);
  return [text(entity.UserPrincipalName), name && suffix ? `${name}@${suffix}` : undefined, text(entity.AccountName), name];
}

function hostCandidates(entity: Row): Array<string | undefined> {
  const hostName = text(entity.HostName);
  const domain = text(entity.DnsDomain);
  return [text(entity.FQDN), hostName && domain ? `${hostName}.${domain}` : undefined, hostName];
}

function unresolvedReason(type: EntityType, entity: Row): UnresolvedEntity {
  if (type === "account") {
    const label = text(entity.DisplayName) ?? text(entity.Name);
    const reason = label
      ? "only a display name is recorded, not a UPN or account name"
      : entity.AadUserId ? "only an Entra object ID is recorded" : entity.Sid ? "only a SID is recorded" : "no usable identifier";
    return label ? { type, reason, label } : { type, reason };
  }
  return { type, reason: "no valid address or hostname recorded" };
}

/**
 * Pulls account, IP and host entities out of SecurityAlert.Entities JSON. Entities with
 * an identifier entity_timeline accepts become pivots; the rest are reported with the
 * reason they cannot be pivoted on (real alerts often carry only a SID, an Entra object
 * ID or a display name).
 */
export function extractPivotEntities(alerts: Row[]): { pivots: PivotEntity[]; unresolved: UnresolvedEntity[] } {
  const pivots = new Map<string, PivotEntity>();
  const unresolved = new Map<string, UnresolvedEntity>();

  for (const alert of alerts) {
    let entities: unknown;
    try {
      entities = typeof alert.Entities === "string" ? JSON.parse(alert.Entities) : alert.Entities;
    } catch {
      continue;
    }
    if (!Array.isArray(entities)) {
      continue;
    }
    for (const entity of entities as Row[]) {
      const kind = String(entity.Type ?? "").toLowerCase();
      const type: EntityType | undefined = kind === "account" ? "account" : kind === "ip" ? "ip" : kind === "host" ? "host" : undefined;
      if (!type) {
        continue;
      }
      const candidates = type === "account" ? accountCandidates(entity) : type === "host" ? hostCandidates(entity) : [text(entity.Address)];
      const value = candidates.find((candidate) => isValidEntity(type, candidate));
      if (value) {
        pivots.set(`${type}:${value.toLowerCase()}`, { type, value });
      } else {
        const entry = unresolvedReason(type, entity);
        unresolved.set(`${type}:${entry.reason}:${entry.label ?? ""}`, entry);
      }
    }
  }
  return { pivots: [...pivots.values()], unresolved: [...unresolved.values()] };
}

export class SocService {
  constructor(
    private readonly runner: WorkspaceQueryRunner,
    private readonly hunting = new HuntingLibrary(),
  ) {}

  async #rows(workspaceId: string, query: string, timespan: string, policy = builtInPolicy) {
    const result = await this.runner.runQuery(workspaceId, query, timespan, policy);
    return { rows: tableToRows(result.tables[0]), truncatedRows: result.tables[0]?.truncatedRows ?? 0, status: result.status };
  }

  async listIncidents(workspaceId: string, timespan: string, filters: IncidentFilters) {
    const { rows } = await this.#rows(workspaceId, listIncidentsQuery(filters), timespan);
    return { count: rows.length, incidents: rows };
  }

  async getIncident(workspaceId: string, incidentNumber: number, timespan: string) {
    const [detail, alerts] = await Promise.all([
      this.#rows(workspaceId, incidentDetailQuery(incidentNumber), timespan),
      this.#rows(workspaceId, incidentAlertsQuery(incidentNumber), timespan),
    ]);
    if (!detail.rows[0]) {
      throw new Error(`KQL query found no incident ${incidentNumber} in the selected timespan. Widen the timespan or check the number.`);
    }
    const { pivots, unresolved } = extractPivotEntities(alerts.rows);
    return {
      incident: detail.rows[0],
      alerts: alerts.rows.map(({ Entities: _entities, ...alert }) => alert),
      pivotEntities: pivots,
      unresolvedEntities: unresolved,
    };
  }

  async entityTimeline(workspaceId: string, entityType: EntityType, entity: string, timespan: string, maxEvents: number) {
    const [summary, events] = await Promise.all([
      this.#rows(workspaceId, entityTimelineSummaryQuery(entityType, entity), timespan),
      this.#rows(workspaceId, entityTimelineQuery(entityType, entity, maxEvents), timespan),
    ]);
    return {
      entity: { type: entityType, value: entity },
      sources: summary.rows,
      totalEvents: summary.rows.reduce((total, row) => total + (Number(row.Events) || 0), 0),
      returnedEvents: events.rows.length,
      events: events.rows,
    };
  }

  async checkIngestionHealth(workspaceId: string, timespan: string, staleAfterHours: number) {
    const [volume, latency] = await Promise.all([
      this.#rows(workspaceId, ingestionVolumeQuery(staleAfterHours), timespan),
      this.#rows(workspaceId, ingestionLatencyQuery(), "PT1H"),
    ]);
    const problems = volume.rows.filter((row) => row.Status !== "Healthy");
    const delayed = latency.rows.filter((row) => Number(row.P95LatencySec) > 900);
    return {
      summary: {
        tables: volume.rows.length,
        stale: problems.filter((row) => row.Status === "Stale").map((row) => row.DataType),
        volumeDrops: problems.filter((row) => row.Status === "VolumeDrop").map((row) => row.DataType),
        volumeSpikes: problems.filter((row) => row.Status === "VolumeSpike").map((row) => row.DataType),
        delayedOver15Min: delayed.map((row) => row.TableName),
      },
      tables: volume.rows,
      latencyLastHour: latency.rows,
    };
  }

  listHuntingQueries() {
    return { queries: this.hunting.list(), loadErrors: this.hunting.loadErrors };
  }

  async runHuntingQuery(workspaceId: string, queryId: string, timespan: string) {
    const hunt = this.hunting.get(queryId);
    const { rows, truncatedRows } = await this.#rows(workspaceId, hunt.query, timespan, HuntingLibrary.policy);
    const { query: _query, ...metadata } = hunt;
    return { hunt: metadata, resultCount: rows.length, truncatedRows, results: rows };
  }
}
